---
# tasks file for awx
- name: Clone awx
  git:
    repo: https://github.com/ansible/awx.git
    dest: /tmp/awx
    force: yes

- name: Change default passwd
  lineinfile:
    path: /tmp/awx/installer/inventory
    regexp: '^admin_password=password'
    line: 'admin_password={{ awx_admin_pwd }}'

- name: Is 80 port free?
  wait_for:
    port: 80
    timeout: 5
    msg: "Waiting for reponse"
  register: port_check
  ignore_errors: yes

- debug:
    var: port_check

- name: User 8080 port
  lineinfile:
    path: /tmp/awx/installer/inventory
    regexp: '^host_port=80'
    line: 'host_port=8080'
  when: port_check.state == "started"

- name: Install ansible
  pip:
    name: ansible

- name: Deploy awx
  shell: "ansible-playbook /tmp/awx/installer/install.yml -i /tmp/awx/installer/inventory" 